---
- name: Playbook
  hosts: localhost
  connection: local
  roles:
    - role: ansible-role-system
      vars:
        hosts_pack: basic
        thinkpad: true
        user: michael
    - role: ansible-role-packages
      vars:
        install_aur_helper: false
        gui:
          enabled: true
          arch:
            - kitty
            # - chromium
            # - clipmenu
            # - firefox
            # - flameshot
            # - libreoffice
            # - manjaro-printer
            # - manjaro-settings-manager
            # - pinta
            # - system-config-printer
            # - wmctrl
            - xbindkeys
            # - zathura
            # - zathura-pdf-mupdf
        cli:
          enabled: true
          common:
            - check
            - clipmenu
            - coreutils
            - dateutils
            - gawk
            - lsof
            - make
            - moreutils
            - rofi
            - sudo
            - tar
            - unzip
            - zip
          debian:
            - build-essential
            - python3-dev
            - libxcb-xrm0
            - dnsutils
            - libx11-dev
            - libxext-dev
            - libxfixes-dev
            - libxfixes-dev
            - libxi-dev
            - libxt-dev
            - ninja-build
            - x11proto-core-dev
            - zeal
          arch:
            - base-devel
            - xcb-util-xrm
            - bind-tools
    # - role: ansible-role-pip
    #   pip_packages:
    #     # - "molecule[docker]"
    #     # - molecule pynacl build fails for macOS
    #     - pandas
    #     - pytest-testinfra
    #     - selenium
    # - role: ansible-role-binaries
    #   vars:
    #     kubectl_version: 1.22.0
    #     pet_version: 0.4.0
    #     tfswitch_version: 0.13.1201
    #     goMarkableClient_version: 0.6.4
    #     binaries:
    #       - name: kubectl
    #         url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/darwin/arm64/kubectl"
    #       - name: pet
    #         url: "https://github.com/knqyf263/pet/releases/download/v{{ pet_version }}/pet_{{ pet_version }}_darwin_arm64.tar.gz"
    #         extract: true
    #       - name: tfswitch
    #         url: "https://github.com/warrensbox/terraform-switcher/releases/download/{{tfswitch_version}}/terraform-switcher_{{tfswitch_version}}_darwin_arm64.tar.gz"
    #         extract: true
    #       - name: gh-md-toc
    #         url: "https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc"
    #         extract: false
    #       - name: goMarkableClient
    #         url: "https://github.com/owulveryck/goMarkableStream/releases/download/v{{goMarkableClient_version}}/goMarkableClient_{{goMarkableClient_version}}_Darwin_arm64.tar.gz"
    #         extract: true
    - role: ansible-role-dotfiles
      # vars:
      # dotfiles:
      # public:
      # repo_url: "git@github.com:allaman/dots.git"
      # private:
      #   enabled: true
      #   repo_url: "git@git.rootknecht.net:allaman/private-dotfiles.git"
      #   path: "{{ ansible_env.HOME }}/workspace/git.rootknecht.net/private-dotfiles"
